services:
  server:
    restart: always
    build:
      context: server
    volumes:
      - /server/myData:/var/lib/docker
    depends_on:
      - mongo
    networks:
      - express-mongo
    ports:
      - 3000:3000
  mongo:
    restart: always
    image: mongo:4.2.0
    volumes:
      - /server/myData:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
    
networks:
  express-mongo:
